### ISSUE TITLE
Add other blockchains for DAI, USDC and USDT

### ISSUE THREAD

**Issue by Wjxfi** [pitonite/exch_cx#1]
I specifically need Polygon. Maybe others will need Avalanche. Or maybe TRON or BNB.

Because without it, it makes no sense to me.

**Comment by pitonite** [comment]
Hi
Thank you for showing interest in eXch.
This is the repository for the app made by me, a community member
For features not related to the app itself, like what you are asking, It's better to contact the exch.cx support through it's website:
https://exch.cx/support

**Comment by Wjxfi** [comment]
Thank you, sorry
