### ISSUE TITLE
error when opening support chat

### ISSUE THREAD

**Issue by ghost** [pitonite/exch_cx#2]
Illegal input:
io.github.pitonite.exch_cx.model.api.SupportMessageSender does not contain element with name 'SYSTEM'

**Comment by pitonite** [comment]
Hi
Thanks for reporting this issue
I will investigate and fix this

**Comment by pitonite** [comment]
a fix has been released on [v1.3.2](https://github.com/pitonite/exch_cx/releases/tag/v1.3.2)
you can download it directly from GitHub and update your app, or wait until it's released on f-droid
both use the same signature, so it doesn't matter from which source you install the app, you can always update by either means
